name: CI Build and Test

on:  
  pull_request:
    branches: [ master, develop ]
  push:
    branches: [ master, develop ] # Added push event to trigger deployment
  workflow_dispatch:
    
permissions:
 contents: read
 issues: read
 checks: write
 pull-requests: write

jobs:
  build-and-test-backend:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'
          
      - name: Restore dependencies
        run: dotnet restore
        
      - name: Build
        run: dotnet build --no-restore
        
      # - name: Start Cosmos DB Emulator
      #   uses: southpolesteve/cosmos-emulator-github-action@v1
        
      - name: Test
        run: dotnet test --no-build --verbosity normal --collect:"XPlat Code Coverage"
        env:
          ASPIRE_ALLOW_UNSECURED_TRANSPORT: true
          
      - name: Generate coverage report
        uses: danielpalme/ReportGenerator-GitHub-Action@5.1.19
        with:
          reports: '**/coverage.cobertura.xml'
          targetdir: 'coveragereport'
          reporttypes: 'HtmlInline_AzurePipelines;Cobertura'
          
      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: backend-coverage-report
          path: coveragereport
          
  build-and-test-frontend:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
          cache: 'npm'
          cache-dependency-path: 'Frontend/package-lock.json'
          
      - name: Install dependencies
        run: |
          cd Frontend
          npm ci
          
      - name: Create Karma config
        run: |
          cat > Frontend/karma.conf.js << 'EOL'
          module.exports = function (config) {
            config.set({
              basePath: '',
              frameworks: ['jasmine', '@angular-devkit/build-angular'],
              plugins: [
                require('karma-jasmine'),
                require('karma-chrome-launcher'),
                require('karma-jasmine-html-reporter'),
                require('karma-coverage'),
                require('@angular-devkit/build-angular/plugins/karma')
              ],
              client: {
                jasmine: {},
                clearContext: false
              },
              jasmineHtmlReporter: {
                suppressAll: true
              },
              coverageReporter: {
                dir: require('path').join(__dirname, './coverage'),
                subdir: '.',
                reporters: [
                  { type: 'html' },
                  { type: 'text-summary' },
                  { type: 'cobertura' }
                ]
              },
              reporters: ['progress', 'kjhtml'],
              browsers: ['Chrome'],
              restartOnFileChange: true,
              customLaunchers: {
                ChromeHeadlessCI: {
                  base: 'ChromeHeadless',
                  flags: ['--no-sandbox', '--disable-gpu']
                }
              }
            });
          };
          EOL
          
      - name: Build Frontend
        run: |
          cd Frontend
          npm run build
          
      - name: Install Chrome
        uses: browser-actions/setup-chrome@latest
          
      - name: Test Frontend
        run: |
          cd Frontend
          npm test -- --watch=false --no-progress --browsers=ChromeHeadlessCI --karma-config=karma.conf.js
        
      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: frontend-test-results
          path: Frontend/coverage
      
      # Upload the built frontend as an artifact for deployment
      - name: Upload frontend build
        uses: actions/upload-artifact@v4
        with:
          name: frontend-build
          path: Frontend/dist/
          
  publish-test-results:
    needs: [build-and-test-backend, build-and-test-frontend]
    runs-on: ubuntu-latest
    if: always()
    
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        
      - name: Display structure of downloaded files
        run: ls -R
        
      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          files: |
            **/test-results.xml
            **/coverage.cobertura.xml
          
      - name: Create combined test summary
        run: |
          echo "# Test Results Summary" > test-summary.md
          echo "" >> test-summary.md
          echo "## Backend Tests" >> test-summary.md
          echo "- Coverage report available in artifacts" >> test-summary.md
          echo "" >> test-summary.md
          echo "## Frontend Tests" >> test-summary.md
          echo "- Coverage report available in artifacts" >> test-summary.md
          
      - name: Upload test summary
        uses: actions/upload-artifact@v4
        with:
          name: test-summary
          path: test-summary.md

  # New job for deploying to Azure Static Web App
  deploy-to-azure:
    needs: [build-and-test-frontend]
    runs-on: ubuntu-latest
    if: github.event_name == 'push' || github.event_name == 'workflow_dispatch' # Only deploy on push to main branches or manual trigger
    
    steps:
      - name: Download frontend build artifact
        uses: actions/download-artifact@v4
        with:
          name: frontend-build
          path: frontend-dist
      
      - name: Display structure of downloaded files
        run: ls -R frontend-dist
      
      - name: Deploy to Azure Static Web App
        id: deploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_WHITE_TREE_05D734F0F }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          # The location of the built app content directory relative to the workflow environment
          app_location: "frontend-dist" 
          # The location of built api directory (not required for our case, using empty string)
          api_location: ""
          # Configure routing for SPA applications
          skip_app_build: true # Skip build process as we've already built the app
          output_location: "" # Not needed since we're providing the built files directly

  # This job ensures we clean up resources in case of PR closures
  close_pull_request:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    
    steps:
      - name: Close deployment for PR
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_WHITE_TREE_05D734F0F }}
          action: "close"
